name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: lostnfound_db_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'
          extensions: mysqli, pdo_mysql
          tools: composer:v2
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
            node-version: '22'
            cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up .env.testing
        run: |
          cp .env.example .env.testing
          sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env.testing
          sed -i 's/DB_DATABASE=:memory:/DB_DATABASE=lostnfound_db_test/' .env.testing
          sed -i 's/DB_USERNAME=null/DB_USERNAME=root/' .env.testing
          sed -i 's/DB_PASSWORD=null/DB_PASSWORD=password/' .env.testing

      - name: Debug .env.testing
        run: cat .env.testing

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            mysqladmin ping -h 127.0.0.1 --silent && break
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Set up .env
        run: cp .env.example .env

      - name: Generate application key
        run: |
          php artisan key:generate --env=testing
          php artisan config:cache --env=testing

      - name: Run Migrations
        run: php artisan migrate --env=testing --force
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: lostnfound_db_test
          DB_USERNAME: root
          DB_PASSWORD: 

      - name: Publish Ziggy Config
        run: php artisan ziggy:generate
      
      - name: Compile Assets
        run: npm run build

      - name: Run tests
        run: php artisan test --env=testing
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: lostnfound_db_test
          DB_USERNAME: root
          DB_PASSWORD: 