name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports: ['3306:3306']
        env:
          MYSQL_DATABASE: lostnfound_db_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'
          extensions: mysqli, pdo_mysql

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist
          npm ci

      - name: Prepare Environment
        run: |
          cp .env.example .env.testing
          php artisan key:generate --env=testing
          php artisan config:cache --env=testing

      - name: Run Migrations
        run: php artisan migrate:fresh --env=testing --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: lostnfound_db_test
          DB_USERNAME: root
          DB_PASSWORD: ''

      - name: Build Assets
        run: |
          npm run build
          php artisan ziggy:generate

      - name: Run Tests
        run: php artisan test --env=testing
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: lostnfound_db_test
          DB_USERNAME: root
          DB_PASSWORD: ''